import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { CometChat } from "@cometchat/chat-sdk-javascript";
import { v4 as uuid } from 'uuid';

export const useChatActionsForSignChat = () => {
    const [user, setUser] = useState<CometChat.User | null>(null);
    const [redirect, setRedirect] = useState(false);
    const navigate = useNavigate();
    const authKey = import.meta.env.VITE_COMETCHAT_AUTH_KEY;

    const logout = () => {
        CometChat.logout().then(() => {
            localStorage.removeItem('cometchat:authToken');
            setUser(null);
            setRedirect(true);
            navigate('/');

        });
    };

    const reAuthenticateUserWithToken = (onSuccess?: () => void) => {
        const authToken = localStorage.getItem('cometchat:authToken');
        if (!authToken) return;

        CometChat.login(authToken).then(
            (LoggedinUser) => {
                setUser(LoggedinUser)
                if (onSuccess) onSuccess();
                console.log("Пользователь залогинен:", user);
            },
            error => console.log("login failed", error)
        );
    };

    const getUser = (onSuccess: () => void) => {
        CometChat.getLoggedinUser().then(
            (loggedInUser) => {
                if (loggedInUser) {
                    setUser(loggedInUser);
                    onSuccess(); // это значит если юзер есть,значит можно двигаться дальше
                } else {
                    reAuthenticateUserWithToken();
                }
            },
            () => reAuthenticateUserWithToken(onSuccess)
        );
    };

    const handleSignUp = (name: string) => {
        const autoGeneratedUID = uuid();
        const newUser = new CometChat.User(autoGeneratedUID);
        newUser.setName(name || 'Anon');

        CometChat.createUser(newUser, authKey).then(() => {
            CometChat.login(autoGeneratedUID, authKey).then((loggedInUser) => {
                const token = loggedInUser.getAuthToken;
                if (token) {
                    localStorage.setItem('cometchat:authToken', token()); //токен является функцией так как мы берем инструкцию по получению токена,а не сразу токен
                    setUser(loggedInUser);
                    navigate('/chatboxes');
                }
            },
                error => console.error("Возникла некая ошибка", error)
            );
        },
            error => console.error("Возникла ошибка при создании юсера", error)
        )
    }




    return {
        user, setUser, redirect, logout, getUser, reAuthenticateUserWithToken,handleSignUp
    };
};