import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { CometChat } from "@cometchat/chat-sdk-javascript";
import { v4 as uuid } from 'uuid';
import { useAuth } from "../context/ChatContext";

export const useChatActionsForSignChat = () => {
    const { user, setUser } = useAuth();
    const [redirect, setRedirect] = useState(false);
    const navigate = useNavigate();
    const authKey = import.meta.env.VITE_COMETCHAT_APIKEY;


    const [isLoggingOut, setIsloggingOut] = useState(false);
    const [isNuking, setIsNuking] = useState(false)

    const logout = () => {

        setIsloggingOut(true);

        CometChat.logout().then(() => {
            localStorage.removeItem('cometchat:authToken');
            setUser(null);
            setRedirect(true);
            navigate('/');

        });
    };

    const reAuthenticateUserWithToken = (onSuccess?: () => void) => {
        const authToken = localStorage.getItem('cometchat:authToken');
        if (!authToken) return;

        CometChat.login(authToken).then(
            (LoggedinUser) => {
                setUser(LoggedinUser)
                if (onSuccess) onSuccess();
                console.log("Пользователь залогинен:", user);
            },
            error => console.log("login failed", error)
        );
    };

    const getUser = (onSuccess: () => void) => {
        CometChat.getLoggedinUser().then(
            (loggedInUser) => {
                if (loggedInUser) {
                    setUser(loggedInUser);
                    onSuccess(); // это значит если юзер есть,значит можно двигаться дальше
                } else {
                    reAuthenticateUserWithToken();
                }
            },
            () => reAuthenticateUserWithToken(onSuccess)
        );
    };

    const handleSignUp = async (name: string) => {
        const autoGeneratedUID = uuid();
        const newUser = new CometChat.User(autoGeneratedUID);
        newUser.setName(name || 'Anon');

        await CometChat.createUser(newUser, authKey).then(() => {

            localStorage.setItem(`anon_uid_${name.toLowerCase()}`, autoGeneratedUID)

            CometChat.login(autoGeneratedUID, authKey).then((loggedInUser) => {
                const token = loggedInUser.getAuthToken();
                if (token) {
                    localStorage.setItem('cometchat:authToken', token);
                    setUser(loggedInUser);
                    navigate('/chatboxes');
                }
            },
                error => console.error("Возникла некая ошибка", error)
            );
        },
            error => console.error("Возникла ошибка при создании юсера", error)
        )
    }

    const nukeEverything = async (guid: string) => {
        setIsNuking(true);

        try {
            const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5000';

            const response = await fetch(`${apiUrl}/nuke-user/${guid}`, {
                method: 'DELETE'
            });

            if (response.ok) {
                localStorage.clear();
                sessionStorage.clear();
                setUser(null);
                navigate('/');
            } else {
                const errorData = await response.json();
                alert(`Ошибка от сервера: ${errorData.message || 'Не удалось удалить'}`);
            }
        } catch (error) {
            console.error('Ошибка при удалении:', error);
            localStorage.clear();
            setUser(null);
            navigate('/');
        } finally {
            setIsNuking(false);
        }
    }

    return {
        user, setUser, redirect, logout, getUser, reAuthenticateUserWithToken, handleSignUp,
        isLoggingOut,
        isNuking, nukeEverything
    };
};